import type { Product, Category, Order, User, Review, Testimonial, FAQ } from '@/types';

export const categories: Category[] = [
  { id: '1', name: 'Electronics', slug: 'electronics', icon: 'Laptop', count: 156 },
  { id: '2', name: 'Clothing', slug: 'clothing', icon: 'Shirt', count: 243 },
  { id: '3', name: 'Home & Living', slug: 'home-living', icon: 'Home', count: 89 },
  { id: '4', name: 'Sports', slug: 'sports', icon: 'Dumbbell', count: 67 },
  { id: '5', name: 'Books', slug: 'books', icon: 'BookOpen', count: 312 },
  { id: '6', name: 'Accessories', slug: 'accessories', icon: 'Watch', count: 198 },
];

export const products: Product[] = [
  {
    id: '1',
    slug: 'wireless-noise-cancelling-headphones',
    title: 'Wireless Noise-Cancelling Headphones',
    description: 'Premium over-ear headphones with active noise cancellation, 30-hour battery life, and crystal-clear audio quality. Features comfortable memory foam ear cushions and foldable design for portability.',
    price: 249.99,
    originalPrice: 349.99,
    images: [
      'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1583394838336-acd977736f90?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1487215078519-e21cc028cb29?w=600&h=600&fit=crop',
    ],
    category: 'Electronics',
    tags: ['headphones', 'wireless', 'noise-cancelling'],
    rating: 4.8,
    reviewCount: 124,
    stock: 45,
    badge: 'Sale',
    specs: { 'Battery Life': '30 hours', 'Driver Size': '40mm', 'Connectivity': 'Bluetooth 5.2', 'Weight': '250g' },
  },
  {
    id: '2',
    slug: 'minimalist-leather-backpack',
    title: 'Minimalist Leather Backpack',
    description: 'Handcrafted genuine leather backpack with padded laptop compartment, multiple organizer pockets, and water-resistant finish. Perfect for work, travel, or everyday use.',
    price: 189.00,
    images: [
      'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1622560480605-d83c853bc5c3?w=600&h=600&fit=crop',
    ],
    category: 'Accessories',
    tags: ['backpack', 'leather', 'minimalist'],
    rating: 4.6,
    reviewCount: 89,
    stock: 23,
    badge: 'New',
    specs: { 'Material': 'Full-grain leather', 'Capacity': '22L', 'Laptop Size': 'Up to 15"', 'Weight': '1.2kg' },
  },
  {
    id: '3',
    slug: 'smart-fitness-watch-pro',
    title: 'Smart Fitness Watch Pro',
    description: 'Advanced fitness tracker with AMOLED display, heart rate monitoring, GPS tracking, sleep analysis, and 7-day battery life. Water-resistant to 50m.',
    price: 299.99,
    originalPrice: 399.99,
    images: [
      'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1546868871-af0de0ae72be?w=600&h=600&fit=crop',
    ],
    category: 'Electronics',
    tags: ['watch', 'fitness', 'smart'],
    rating: 4.7,
    reviewCount: 256,
    stock: 67,
    badge: 'Hot',
    specs: { 'Display': '1.4" AMOLED', 'Battery': '7 days', 'Water Resistance': '50m', 'Sensors': 'HR, SpO2, GPS' },
  },
  {
    id: '4',
    slug: 'premium-cotton-hoodie',
    title: 'Premium Cotton Hoodie',
    description: 'Ultra-soft 100% organic cotton hoodie with relaxed fit, kangaroo pocket, and ribbed cuffs. Available in multiple colors. Pre-shrunk and fade-resistant.',
    price: 79.99,
    images: [
      'https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1578768079052-aa76e52ff62e?w=600&h=600&fit=crop',
    ],
    category: 'Clothing',
    tags: ['hoodie', 'cotton', 'casual'],
    rating: 4.5,
    reviewCount: 178,
    stock: 120,
    specs: { 'Material': '100% Organic Cotton', 'Fit': 'Relaxed', 'Weight': '400gsm', 'Care': 'Machine wash cold' },
  },
  {
    id: '5',
    slug: 'mechanical-gaming-keyboard',
    title: 'Mechanical Gaming Keyboard',
    description: 'Full-size mechanical keyboard with Cherry MX switches, per-key RGB lighting, dedicated media controls, and aircraft-grade aluminum frame.',
    price: 159.99,
    originalPrice: 199.99,
    images: [
      'https://images.unsplash.com/photo-1541140532154-b024d705b90a?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1595225476474-87563907a212?w=600&h=600&fit=crop',
    ],
    category: 'Electronics',
    tags: ['keyboard', 'gaming', 'mechanical'],
    rating: 4.9,
    reviewCount: 342,
    stock: 38,
    badge: 'Sale',
    specs: { 'Switch Type': 'Cherry MX Red', 'Layout': 'Full-size (104 keys)', 'Backlighting': 'Per-key RGB', 'Connection': 'USB-C' },
  },
  {
    id: '6',
    slug: 'ceramic-pour-over-coffee-set',
    title: 'Ceramic Pour-Over Coffee Set',
    description: 'Artisan-crafted ceramic pour-over dripper with matching carafe and four cups. Features a micro-perforated filter for clean, rich coffee extraction.',
    price: 64.99,
    images: [
      'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1514432324607-a09d9b4aefda?w=600&h=600&fit=crop',
    ],
    category: 'Home & Living',
    tags: ['coffee', 'ceramic', 'pour-over'],
    rating: 4.4,
    reviewCount: 56,
    stock: 34,
    badge: 'New',
    specs: { 'Material': 'Stoneware ceramic', 'Capacity': '600ml carafe', 'Pieces': '6-piece set', 'Dishwasher': 'Safe' },
  },
  {
    id: '7',
    slug: 'ultralight-running-shoes',
    title: 'Ultralight Running Shoes',
    description: 'Engineered mesh upper with adaptive support and responsive cushioning. Featuring carbon fiber plate for energy return and grip tread outsole.',
    price: 139.99,
    originalPrice: 179.99,
    images: [
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=600&h=600&fit=crop',
    ],
    category: 'Sports',
    tags: ['shoes', 'running', 'lightweight'],
    rating: 4.6,
    reviewCount: 203,
    stock: 89,
    badge: 'Hot',
    specs: { 'Weight': '198g', 'Drop': '8mm', 'Upper': 'Engineered mesh', 'Sole': 'Carbon fiber plate' },
  },
  {
    id: '8',
    slug: 'design-thinking-essentials',
    title: 'Design Thinking Essentials',
    description: 'A comprehensive guide to design thinking methodology with real-world case studies, practical exercises, and frameworks for innovation.',
    price: 34.99,
    images: [
      'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=600&h=600&fit=crop',
    ],
    category: 'Books',
    tags: ['design', 'business', 'creativity'],
    rating: 4.3,
    reviewCount: 91,
    stock: 200,
    specs: { 'Pages': '384', 'Format': 'Hardcover', 'Language': 'English', 'ISBN': '978-0-12345-678-9' },
  },
  {
    id: '9',
    slug: 'wireless-charging-pad-duo',
    title: 'Wireless Charging Pad Duo',
    description: 'Dual wireless charging pad with 15W fast charging, LED indicators, and anti-slip surface. Charges phone and earbuds simultaneously.',
    price: 49.99,
    originalPrice: 69.99,
    images: [
      'https://images.unsplash.com/photo-1586953208270-767889fa9b6f?w=600&h=600&fit=crop',
    ],
    category: 'Electronics',
    tags: ['charger', 'wireless', 'fast-charging'],
    rating: 4.2,
    reviewCount: 167,
    stock: 78,
    badge: 'Sale',
    specs: { 'Power': '15W per pad', 'Input': 'USB-C', 'Compatibility': 'Qi-enabled devices', 'Indicator': 'LED status' },
  },
  {
    id: '10',
    slug: 'bamboo-desk-organizer',
    title: 'Bamboo Desk Organizer',
    description: 'Sustainable bamboo desk organizer with compartments for pens, phone stand, cable management, and a small drawer. Minimalist workspace essential.',
    price: 44.99,
    images: [
      'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=600&h=600&fit=crop',
    ],
    category: 'Home & Living',
    tags: ['desk', 'organizer', 'bamboo'],
    rating: 4.5,
    reviewCount: 73,
    stock: 56,
    badge: 'New',
    specs: { 'Material': 'Moso bamboo', 'Dimensions': '30×15×12cm', 'Compartments': '5', 'Finish': 'Natural oil' },
  },
  {
    id: '11',
    slug: 'premium-yoga-mat',
    title: 'Premium Yoga Mat',
    description: 'Extra-thick 6mm natural rubber yoga mat with alignment lines, non-slip surface on both sides, and carrying strap. Eco-friendly and biodegradable.',
    price: 89.99,
    images: [
      'https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=600&h=600&fit=crop',
    ],
    category: 'Sports',
    tags: ['yoga', 'mat', 'fitness'],
    rating: 4.7,
    reviewCount: 145,
    stock: 67,
    specs: { 'Thickness': '6mm', 'Material': 'Natural rubber', 'Dimensions': '183×68cm', 'Weight': '2.5kg' },
  },
  {
    id: '12',
    slug: 'vintage-canvas-messenger-bag',
    title: 'Vintage Canvas Messenger Bag',
    description: 'Waxed canvas messenger bag with leather accents, brass hardware, and padded laptop sleeve. Water-resistant and built to age beautifully.',
    price: 119.99,
    originalPrice: 149.99,
    images: [
      'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600&h=600&fit=crop',
    ],
    category: 'Accessories',
    tags: ['bag', 'messenger', 'canvas'],
    rating: 4.4,
    reviewCount: 98,
    stock: 31,
    badge: 'Sale',
    specs: { 'Material': 'Waxed canvas + leather', 'Laptop': 'Up to 14"', 'Closure': 'Magnetic flap', 'Strap': 'Adjustable' },
  },
];

export const reviews: Review[] = [
  { id: '1', userId: '1', productId: '1', rating: 5, comment: 'Incredible sound quality and the noise cancellation is top-notch. Best headphones I have ever owned.', createdAt: '2026-02-15', userName: 'Alex Johnson', userAvatar: undefined },
  { id: '2', userId: '2', productId: '1', rating: 4, comment: 'Great headphones overall. Comfortable for long sessions. Battery life is amazing.', createdAt: '2026-02-10', userName: 'Sarah Mitchell' },
  { id: '3', userId: '3', productId: '1', rating: 5, comment: 'Worth every penny. The build quality is exceptional.', createdAt: '2026-01-28', userName: 'Mike Chen' },
  { id: '4', userId: '4', productId: '3', rating: 5, comment: 'This watch tracks everything perfectly. The AMOLED display is gorgeous.', createdAt: '2026-02-20', userName: 'Emma Wilson' },
  { id: '5', userId: '5', productId: '5', rating: 5, comment: 'The best keyboard I have ever typed on. Cherry MX Reds are so smooth.', createdAt: '2026-02-18', userName: 'David Park' },
  { id: '6', userId: '6', productId: '2', rating: 4, comment: 'Beautiful leather quality. Fits my 14 inch laptop perfectly.', createdAt: '2026-02-12', userName: 'Lisa Anderson' },
  { id: '7', userId: '7', productId: '7', rating: 5, comment: 'Lightest shoes I have ever run in. The carbon plate makes a noticeable difference.', createdAt: '2026-02-05', userName: 'James Taylor' },
  { id: '8', userId: '8', productId: '4', rating: 4, comment: 'Super soft and cozy. The organic cotton feels premium. Runs a bit large.', createdAt: '2026-01-30', userName: 'Rachel Green' },
];

export const users: User[] = [
  { id: '1', name: 'Alex Johnson', email: 'alex@example.com', role: 'admin', joinedAt: '2025-06-15', status: 'active' },
  { id: '2', name: 'Sarah Mitchell', email: 'sarah@example.com', role: 'user', joinedAt: '2025-09-20', status: 'active' },
  { id: '3', name: 'Mike Chen', email: 'mike@example.com', role: 'user', joinedAt: '2025-11-03', status: 'active' },
  { id: '4', name: 'Emma Wilson', email: 'emma@example.com', role: 'user', joinedAt: '2025-12-01', status: 'active' },
  { id: '5', name: 'David Park', email: 'david@example.com', role: 'user', joinedAt: '2026-01-10', status: 'active' },
  { id: '6', name: 'Lisa Anderson', email: 'lisa@example.com', role: 'user', joinedAt: '2026-01-22', status: 'banned' },
  { id: '7', name: 'James Taylor', email: 'james@example.com', role: 'user', joinedAt: '2026-02-01', status: 'active' },
  { id: '8', name: 'Rachel Green', email: 'rachel@example.com', role: 'user', joinedAt: '2026-02-14', status: 'active' },
];

export const orders: Order[] = [
  {
    id: 'ORD-001',
    userId: '2',
    items: [{ ...products[0], quantity: 1 }, { ...products[3], quantity: 2 }],
    total: 409.97,
    status: 'delivered',
    createdAt: '2026-02-20',
    shippingAddress: { fullName: 'Sarah Mitchell', line1: '123 Main St', city: 'New York', state: 'NY', zip: '10001', country: 'US' },
  },
  {
    id: 'ORD-002',
    userId: '3',
    items: [{ ...products[4], quantity: 1 }],
    total: 159.99,
    status: 'shipped',
    createdAt: '2026-02-22',
    shippingAddress: { fullName: 'Mike Chen', line1: '456 Oak Ave', city: 'San Francisco', state: 'CA', zip: '94102', country: 'US' },
  },
  {
    id: 'ORD-003',
    userId: '4',
    items: [{ ...products[2], quantity: 1 }, { ...products[8], quantity: 1 }],
    total: 349.98,
    status: 'processing',
    createdAt: '2026-02-25',
    shippingAddress: { fullName: 'Emma Wilson', line1: '789 Pine Rd', city: 'Chicago', state: 'IL', zip: '60601', country: 'US' },
  },
  {
    id: 'ORD-004',
    userId: '5',
    items: [{ ...products[6], quantity: 1 }],
    total: 139.99,
    status: 'processing',
    createdAt: '2026-02-26',
    shippingAddress: { fullName: 'David Park', line1: '321 Elm St', city: 'Austin', state: 'TX', zip: '73301', country: 'US' },
  },
  {
    id: 'ORD-005',
    userId: '7',
    items: [{ ...products[1], quantity: 1 }, { ...products[5], quantity: 1 }],
    total: 253.99,
    status: 'cancelled',
    createdAt: '2026-02-18',
    shippingAddress: { fullName: 'James Taylor', line1: '654 Maple Dr', city: 'Seattle', state: 'WA', zip: '98101', country: 'US' },
  },
];

export const testimonials: Testimonial[] = [
  { id: '1', name: 'Jessica Williams', role: 'Product Designer', quote: 'The quality of products and the shopping experience is unmatched. I have been a loyal customer for over a year now and every purchase has exceeded my expectations.', rating: 5 },
  { id: '2', name: 'Robert Kim', role: 'Software Engineer', quote: 'Lightning-fast delivery and the customer support team is incredibly responsive. The product range is impressive with great attention to quality.', rating: 5 },
  { id: '3', name: 'Amanda Torres', role: 'Freelance Writer', quote: 'Finally found a marketplace that values both quality and design. The curated collection makes it easy to find exactly what you need without endless scrolling.', rating: 4 },
];

export const faqs: FAQ[] = [
  { id: '1', question: 'How long does shipping take?', answer: 'Standard shipping takes 5-7 business days. Express shipping is available for 2-3 business day delivery. Free shipping on all orders over $50.' },
  { id: '2', question: 'What is your return policy?', answer: 'We offer a 30-day hassle-free return policy. Items must be in original condition with tags attached. Refunds are processed within 5 business days of receiving the return.' },
  { id: '3', question: 'Do you ship internationally?', answer: 'Yes! We ship to over 50 countries worldwide. International shipping typically takes 7-14 business days depending on the destination.' },
  { id: '4', question: 'How can I track my order?', answer: 'Once your order ships, you will receive an email with a tracking number. You can also track your order in real-time from your dashboard under "My Orders".' },
  { id: '5', question: 'Are your products guaranteed?', answer: 'All products come with a minimum 1-year warranty against manufacturing defects. Premium electronics include an extended 2-year warranty at no extra cost.' },
  { id: '6', question: 'Can I modify or cancel my order?', answer: 'Orders can be modified or cancelled within 2 hours of placement. After that, please contact our support team and we will do our best to accommodate your request.' },
];

export const adminStats = {
  revenue: { value: '$48,259', trend: '+12.5%', trendUp: true },
  orders: { value: '1,247', trend: '+8.2%', trendUp: true },
  products: { value: '356', trend: '+3.1%', trendUp: true },
  users: { value: '8,492', trend: '+15.7%', trendUp: true },
};

export const salesData = Array.from({ length: 30 }, (_, i) => ({
  date: `Feb ${i + 1}`,
  revenue: Math.floor(Math.random() * 3000) + 800,
  orders: Math.floor(Math.random() * 50) + 10,
}));
